still trying to get the POS /bin/sh in solaris to run all the scripts. Not there yet and probably not caring anymore.

diff --git a/test/create b/test/create
--- a/test/create
+++ b/test/create
@@ -11,8 +11,8 @@ out=/tmp/create_test.out$$
 pw=abcdefg
 
 # create a new empty database
-[ ! -e $file ] || rm $file
-if [ -e $file ]; then
+[ ! -f $file ] || rm $file
+if [ -f $file ]; then
   echo "Can't clean up $file. Please delete it yourself and then rerun this test"
   exit 1
 fi
@@ -88,12 +88,27 @@ $cmdline 2>$err 1>$out <<EOF
 $pw
 EOF
 
-if [ $? -ne 0 ] || ! grep <$out \
-"# passwordsafe version 2.0 database
-uuid	group	name	login	passwd	notes
-........-....-....-....-............	test_group	test_name	test_login	test_pw	test_notes" >/dev/null ; then
+if [ $? -ne 0 ]; then
   echo "FAILED!"
   echo "pwsafe is NOT WORKING PROPERLY. It is unable to read back its new entry in $file (passphrase: $pw)."
+  echo "Here is the cmdline:"
+  echo "$cmdline"
+  echo "Here is the output:"
+  cat $out
+  cat $err
+  exit 1
+fi
+
+grep <$out "# passwordsafe version 2.0 database" >/dev/null
+RC=$?
+grep <$out "^uuid	group	name	login	passwd	notes" >/dev/null
+RC="$RC$?"
+grep <$out '^"........-....-....-....-............"	"test_group"	"test_name"	"test_login"	"test_pw"	"test_notes"' >/dev/null
+RC="$RC$?"
+
+if [ $RC -ne 0 ]; then
+  echo "FAILED!"
+  echo "pwsafe is NOT WORKING PROPERLY. Did not find expected output when reading back new entry in $file (passphrase: $pw)."
   echo "Here is the cmdline:"
   echo "$cmdline"
   echo "Here is the output:"
diff --git a/test/edit b/test/edit
--- a/test/edit
+++ b/test/edit
@@ -10,8 +10,8 @@ err=/tmp/edit_test.err$$
 pw=abc
 
 # create a new empty database
-[ ! -e $file ] || rm $file
-if [ -e $file ]; then
+[ ! -f $file ] || rm $file
+if [ -f $file ]; then
   echo "Can't clean up $file. Please delete it yourself and then rerun this test"
   exit 1
 fi
@@ -34,7 +34,7 @@ $cmdline 2>$err 1>&2 <<EOF
 $pw
 EOF
 
-if [ $? -ne 1 ] || ! (cat $err | grep 'does_not_exist not found$' >/dev/null ) || ! ( cat $err | grep "$file unchanged\$" >/dev/null ) ; then
+if [ $? -ne 1 -o `cat $err | grep 'does_not_exist not found$' >/dev/null; echo $?` -ne 0 -o `cat $err | grep "$file unchanged\$" >/dev/null; echo $?` -ne 0 ]; then
   echo "FAILED!"
   echo "pwsafe is NOT WORKING PROPERLY. It is not properly failing to remove a non-existant entry from $file (passphrase: $pw)."
   echo "Here is the cmdline:"
@@ -54,8 +54,7 @@ abc
 new_name
 new_group
 new_username
-y
-yy
+
 
 y
 EOF
