fleshed out merge and edit tests

diff --git a/test/edit b/test/edit
--- a/test/edit
+++ b/test/edit
@@ -33,7 +33,7 @@ out=`$pwsafe 2>$err --delete does_not_exist -f $file <<EOF
 $pw
 EOF
 `
-if [ $? -ne 1 ] || ! (echo "$out" | grep '^does_not_exist not found$' >/dev/null ) ! ( echo "$out" | grep "$file unchanged\$" >/dev/null ) ; then
+if [ $? -ne 1 ] || ! (cat $err | grep 'does_not_exist not found$' >/dev/null ) || ! ( cat $err | grep "$file unchanged\$" >/dev/null ) ; then
   echo "FAILED!"
   echo "pwsafe is NOT WORKING PROPERLY. It is not properly failing to remove a non-existant entry from $file (passphrase: $pw)."
   echo "Here is the output:"
@@ -48,9 +48,16 @@ fi
 echo -n "testing editing 'testing' entry in $file: "
 out=`$pwsafe 2>$err --edit testing -f $file <<EOF
 abc
+new_name
+new_group
+new_username
+y
+yy
+
+y
 EOF
 `
-if [ $? -ne 0 -o "$out" != "" ]; then
+if [ $? -ne 0 ]; then
   echo "FAILED!"
   echo "pwsafe is NOT WORKING PROPERLY. It is not correctly editing testing entry in $file (passphrase: $pw)."
   echo "Here is the output:"
@@ -63,13 +70,13 @@ fi
 
 # remove an existing entry
 echo -n "testing removing 'testing' entry from $file: "
-out=`$pwsafe 2>$err --delete testing -f $file <<EOF
+out=`$pwsafe 2>$err --delete new_group.new_name -f $file <<EOF
 $pw
 EOF
 `
 if [ $? -ne 0 ]; then
   echo "FAILED!"
-  echo "pwsafe is NOT WORKING PROPERLY. It is not removing testing entry from $file (passphrase: $pw)."
+  echo "pwsafe is NOT WORKING PROPERLY. It is not removing 'new_group.new_name' entry from $file (passphrase: $pw)."
   echo "Here is the output:"
   echo "$out"
   cat $err
diff --git a/test/merge b/test/merge
--- a/test/merge
+++ b/test/merge
@@ -5,9 +5,98 @@ if [ -z "$srcdir" ]; then
 fi
 
 pwsafe=$srcdir/pwsafe
-file=/tmp/create_test.dat$$
-err=/tmp/create_test.err$$
-pw=abcdefg
+file=/tmp/merge_test.dat$$
+err=/tmp/merge_test.err$$
+pw=abc
+
+# create a db, and merge test.dat into it
+[ ! -e $file ] || rm $file
+if [ -e $file ]; then
+  echo "Can't clean up $file. Please delete it yourself and then rerun this test"
+  exit 1
+fi
+
+echo -n "creating a new db $file: "
+$pwsafe 2>$err 1>&2 --createdb -f $file << EOF
+$pw
+$pw
+EOF
+if [ $? -ne 0 ]; then
+  echo "FAILED!"
+  echo "Unable to create $file"
+  exit 1
+else
+  echo OK
+fi
+
+echo -n "merging testv2.dat into $file: "
+out=`$pwsafe 2>$err --mergedb $srcdir/testv2.dat -f $file <<EOF
+$pw
+EOF
+`
+if [ $? -ne 0 ] || ! (echo "$out" | grep >/dev/null "Merged 1 entries; skipped 0; 0 duplicates." ); then
+  echo "FAILED!"
+  echo "Unable to merge testv2.dat into $file"
+  echo "Here is the output:"
+  echo "$out"
+  cat $err
+  exit 1
+else
+  echo OK
+fi
+
+
+echo -n "re-merging testv2.dat into $file another time: "
+out=`$pwsafe 2>$err --mergedb $srcdir/testv2.dat -f $file <<EOF
+$pw
+EOF
+`
+if [ $? -ne 0 ] || ! (echo "$out" | grep >/dev/null "Merged 0 entries; skipped 0; 1 duplicates." ); then
+  echo "FAILED!"
+  echo "Unable to re-merge testv2.dat into $file"
+  echo "Here is the output:"
+  echo "$out"
+  cat $err
+  exit 1
+else
+  echo OK
+fi
+
+echo -n "merging test.dat into $file: "
+out=`$pwsafe 2>$err --mergedb $srcdir/test.dat -f $file <<EOF
+$pw
+n
+EOF
+`
+if [ $? -ne 0 ] || ! (echo "$out" | grep >/dev/null "Merged 0 entries; skipped 1; 0 duplicates." ); then
+  echo "FAILED!"
+  echo "Unable to merge test.dat into $file"
+  echo "Here is the output:"
+  echo "$out"
+  cat $err
+  exit 1
+else
+  echo OK
+fi
+
+
+echo -n "merging $file with itself: "
+out=`$pwsafe 2>$err --mergedb $file -f $file <<EOF
+$pw
+y
+EOF
+`
+if [ $? -ne 0 ] || ! (echo "$out" | grep >/dev/null "Merged 0 entries; skipped 0; 1 duplicates." ); then
+  echo "FAILED!"
+  echo "Unable to merge $file with itself"
+  echo "Here is the output:"
+  echo "$out"
+  cat $err
+  exit 1
+else
+  echo OK
+fi
+
 
 # cleanup after ourselves
 rm $file $file~ $err
